image: openshift/jenkins-slave-base-centos7

stages:
  - build
  - deploy
  - autotest
  - canary

before_script:
  - oc login --insecure-skip-tls-verify=true kubernetes.default.svc --token=$OPENSHIFT_TOKEN
  - oc project blue-green
  - export TAG="blue"
  - export ALTTAG="green"
  - export ACTIVE=$(oc get route prod-route -o jsonpath='{ .spec.to.name }' --loglevel=4)
  - if [ $ACTIVE == "blue" ]; then export TAG="green" ALTTAG="blue"; fi
  - export TAGHOST="$TAG.blue-green.svc"

build:
  stage: build
  script:
    - oc start-build blue-green --wait

deploy:
  stage: deploy
  script:
    - oc tag blue-green:latest blue-green:${TAG}
    - oc rollout latest dc/${TAG}

autotest:
  stage: autotest
  script:
    - curl -kLs http://${TAGHOST}:8080/ | tee | grep 'Anonymous'
    - curl -kLs http://${TAGHOST}:8080/containers | tee | grep 'containers'
    - curl -kLs http://${TAGHOST}:8080/Питер | tee | grep 'Питер'

canary:
  stage: canary
  script:
    - for i in `seq 10 10 100` do; oc set route-backends prod-route ${TAG}=$i ${ALTTAG}=$(100-i) --loglevel=4 && sleep 10; done
