image: openshift/jenkins-slave-base-centos7

stages:
  - build

variables:
  # Configure these variables in Secure Variables:
  # OPENSHIFT_SERVER: https://openshift.domain.com:8443
  # OPENSHIFT_TOKEN: my.openshift.token
  # OPENSHIFT_DOMAIN: routes.openshift.domain.com

before_script:
  - ls -la
  - env
  - which oc
  - echo $OPENSHIFT_TOKEN
  - oc login --insecure-skip-tls-verify=true kubernetes.default.svc --token=$OPENSHIFT_TOKEN
  - oc get pods

build:
  stage: build
  script:
    - echo build
