apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
        openshift.io/image.dockerRepositoryCheck: 2018-02-15T11:18:29Z
      creationTimestamp: null
      generation: 2
      labels:
        app: openshift-demo
      name: fedora
    spec:
      lookupPolicy:
        local: false
      tags:
      - annotations:
          openshift.io/imported-from: fedora:27
        from:
          kind: DockerImage
          name: registry.fedoraproject.org/fedora:27
        generation: 2
        importPolicy: {}
        name: "27"
        referencePolicy:
          type: Source
    status:
      dockerImageRepository: ""
  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      generation: 1
      labels:
        app: openshift-demo
      name: openshift-demo
    spec:
      lookupPolicy:
        local: false
      tags:
      - annotations: null
        from:
          kind: DockerImage
          name: 172.30.1.1:5000/myproject/openshift-demo:latest
        generation: null
        importPolicy: {}
        name: latest
        referencePolicy:
          type: ""
    status:
      dockerImageRepository: ""
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: openshift-demo
      name: openshift-demo
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: openshift-demo:latest
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        git:
          ref: openshift
          uri: https://github.com/vrutkovs/draft-demo.git
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: fedora:27
        type: Docker
      successfulBuildsHistoryLimit: 5
      triggers:
      - github:
          secret: BhsyIluB4mv2YsN9bWlW
        type: GitHub
      - generic:
          secret: S2smj9q-1sUupFwHKbi1
        type: Generic
      - type: ConfigChange
      - imageChange: {}
        type: ImageChange
    status:
      lastVersion: 0
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      generation: 1
      labels:
        app: openshift-demo
      name: openshift-demo
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        app: openshift-demo
        deploymentconfig: openshift-demo
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          creationTimestamp: null
          labels:
            app: openshift-demo
            deploymentconfig: openshift-demo
        spec:
          containers:
          - image: 172.30.1.1:5000/myproject/openshift-demo@sha256:b530f236939ad7883413f292b0a7df750d8bb4098d345ad00a3fc9a2102d9bf2
            imagePullPolicy: Always
            name: openshift-demo
            ports:
            - containerPort: 8080
              protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - openshift-demo
          from:
            kind: ImageStreamTag
            name: openshift-demo:latest
            namespace: myproject
        type: ImageChange
    status:
      availableReplicas: 0
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      unavailableReplicas: 0
      updatedReplicas: 0
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: openshift-demo
      name: openshift-demo
    spec:
      ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
      selector:
        app: openshift-demo
        deploymentconfig: openshift-demo
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Route
    metadata:
      creationTimestamp: null
      labels:
        app: openshift-demo
      name: openshift-demo
    spec:
      host: openshift.127.0.0.1.xip.io
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: openshift-demo
        weight: 100
      wildcardPolicy: None
    status:
      ingress:
      - conditions:
        - lastTransitionTime: 2018-02-15T11:24:14Z
          status: "True"
          type: Admitted
        host: openshift.127.0.0.1.xip.io
        routerName: router
        wildcardPolicy: None
