apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: pipeline-app
  name: pipeline-app
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: pipeline-app:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: http://github.com/vrutkovs/openshift-demo
      ref: jenkins
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: fedora:27
        namespace: pipelines
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - generic:
      secret: 5vidEKDbc9iodkCoUdxS
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
