apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 1
  labels:
    app: pipeline-app
  name: pipeline-app
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    generation: null
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""
  - annotations: null
    generation: null
    importPolicy: {}
    name: smoketested
    referencePolicy:
      type: ""
status:
  dockerImageRepository: ""
